[options]
HoldPkg     = pacman glibc
Architecture = auto

CheckSpace
ParallelDownloads = 5
DownloadUser = alpm

SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[TIMW-AUR]
SigLevel = Never
Server = https://github.com/TIMW-AUR/TIMW-AUR/releases/download/TIMW-AUR

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist
